server:
  port: 9988
  servlet:
    session:
      cookie:
        name: MISESSIONID
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
spring:
  application:
    name: authentication
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://167.71.198.93/sample
    username: lambda
    password: lambda
  data:
    mongodb:
      uri: mongodb://167.71.198.93/tokens

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
eureka:
  client:
    service-url:
#      defaultZone: http://167.71.198.93:8761/eureka
      defaultZone: http://localhost:8761/eureka
debug: true
