eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    healthcheck:
      enable: true
  service-url:
    defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
server:
  port: 8761
debug: true
