version: '3'

services:
  config-server:
    image: openjdk:8
    working_dir: /app
    volumes:
      - $PWD/config-server/build:/app
    command: /bin/bash -c "java -jar libs/*.jar"
    links:
      - service-registry
    depends_on:
      - service-registry
  service-registry:
    image: openjdk:8
    working_dir: /app
    volumes:
      - $PWD/service-registry/build:/app
    command: /bin/bash -c "java -jar libs/*.jar"
    ports:
      - "8761:8761"

  mysql-db:
    image: openjdk:8
    working_dir: /app
    volumes:
      - $PWD/mysql-db/build:/app
    command: /bin/bash -c "java -jar libs/*.jar"
    links:
      - db
    depends_on:
      - service-registry
      - db

  front-end:
    image: node
    working_dir: /app
    volumes:
      - $PWD/front-end:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: /bin/bash -c "npm install --silent; npm start"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lambda
      MYSQL_USER: lambda
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_HOST: '%'
