server:
  port: 0
spring:
  application:
    name: mysql_db
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/lambda
    username: root
    password: password
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    
eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka
